### ISSUE TITLE
Cassandra not responding & docker-compose not working

### ISSUE THREAD

**Issue by kdawgwilk** [yep/usergrid-docker#1]
Cassandra seems to not be starting properly.  It also cannot be shutdown unless the VM is restarted :(

OS: OS X 10.11.3
Docker Version: 1.9.1

I also was trying to get a docker-compose.yml file working to start in a single command here is what I have so far:

``` yaml
cassandra:
  container_name: cassandra
  image: yep1/usergrid-cassandra
  volumes:
    - ./cassandra-data:/var/lib/cassandra
elasticsearch:
  container_name: elasticsearch
  image: yep1/usergrid-elasticsearch
  volumes:
    - ./elasticsearch-data:/data
usergrid:
  container_name: usergrid
  image: yep1/usergrid
  ports:
    - "8080:8080"
  environment:
    - ADMIN_PASS=password
    - ORG_NAME=org
    - APP_NAME=app
    - ADMIN_USER=admin
    - ADMIN_MAIL=me@example.com
  links:
    - elasticsearch
    - cassandra
portal:
  container_name: portal
  image: yep1/usergrid-portal
  ports:
    - "80:80"
  environment:
    - USERGRID_HOST=usergrid:8080
  links:
    - usergrid
```

USERGRID_HOST doesn't seem to work with the link

**Comment by yep** [comment]
Yes, USERGRID_HOST does not work with the link. The usergrid portal, written in javascript, has to know how to reach the usergrid API. The portal contains a `config.js` file in its root path to define the usegrid API endpoint. On container startup, the contents of the USERGRID_HOST variable is put there.
That means you have to pass the public reachable IP of the machine the usergrid container is running on as USERGRID_HOST.

The following docker-compose yaml works for me:

```
cassandra:
  container_name: cassandra
  image: yep1/usergrid-cassandra
  volumes:
    - ./cassandra-data:/var/lib/cassandra
elasticsearch:
  container_name: elasticsearch
  image: yep1/usergrid-elasticsearch
  volumes:
    - ./elasticsearch-data:/data
usergrid:
  container_name: usergrid
  image: yep1/usergrid
  ports:
    - "8080:8080"
  environment:
    - ORG_NAME=org
    - APP_NAME=app
    - ADMIN_USER=admin
    - ADMIN_PASS=password
    - ADMIN_MAIL=me@example.com
  links:
    - elasticsearch
    - cassandra
portal:
  container_name: portal
  image: yep1/usergrid-portal
  ports:
    - "80:80"
  environment:
    - USERGRID_HOST=public_reachable_ip_of_docker_host_goes_here:8080
```

There was also a problem with usergrid container stopping immediately, fixed in https://github.com/yep/usergrid-docker/commit/cb7b5ab2a148b26aa700dda7d81cb97af9d4caa9

**Comment by SinghPrakash0206** [comment]
Hi,

I tried using your docker-compose file but keep on getting the below error:

cassandra.connection.CassandraHostRetryService.verifyConnection(217)<Hector.me.prettyprint.cassandra.connection.CassandraHostRetryService-1>- Downed :(:):9160 host still appears to be down: Unable to open transport to :(:):9160 , java.net.UnknownHostException: :
usergrid         | +++ waiting for cassandra being available to usergrid

My docker-compose.yml is:

version: '2'

services:
 cassandra:
  container_name: cassandra
  image: yep1/usergrid-cassandra:14.04
  volumes:
    - ./cassandra-data:/var/lib/cassandra
 elasticsearch:
  container_name: elasticsearch
  image: yep1/usergrid-elasticsearch:14.04
  volumes:
    - ./elasticsearch-data:/data
 usergrid:
  container_name: usergrid
  image: yep1/usergrid
  ports:
    - "8080:8080"
  environment:
    - ORG_NAME=org
    - APP_NAME=app
    - ADMIN_USER=admin
    - ADMIN_PASS=password
    - ADMIN_MAIL=me@anant.us
  links:
    - elasticsearch
    - cassandra
 portal:
  container_name: portal
  image: yep1/usergrid-portal
  ports:
    - "80:80"
  environment:
    - USERGRID_HOST=192.168.99.100:8080

**Comment by YMonnier** [comment]
Same issue from my side...

@SinghPrakash0206 did you fix it?
